In [ ]:
# importing pandas library
# importing pandas library
import pandas as pd

In [14]:
# importing dataset
df = pd.read_csv("HR_Analytics.csv")
print("dataset loaded")

dataset loaded

In [15]:
df

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,RM412,60,55+,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,...,4,80,0,33,5,1,29,8,11,10.0
1476,RM428,60,55+,No,Travel_Frequently,1499,Sales,28,3,Marketing,...,4,80,0,22,5,4,18,13,13,11.0
1477,RM537,60,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,...,4,80,0,10,1,3,2,2,2,2.0
1478,RM880,60,55+,No,Travel_Rarely,696,Sales,7,4,Marketing,...,2,80,1,12,3,3,11,7,1,9.0
1479,RM1210,60,55+,No,Travel_Rarely,370,Research & Development,1,4,Medical,...,3,80,1,19,2,4,1,0,0,0.0

In [4]:
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

In [5]:
df.tail()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1475,RM412,60,55+,No,Travel_Rarely,422,Research & Development,7,3,Life Sciences,...,4,80,0,33,5,1,29,8,11,10.0
1476,RM428,60,55+,No,Travel_Frequently,1499,Sales,28,3,Marketing,...,4,80,0,22,5,4,18,13,13,11.0
1477,RM537,60,55+,No,Travel_Rarely,1179,Sales,16,4,Marketing,...,4,80,0,10,1,3,2,2,2,2.0
1478,RM880,60,55+,No,Travel_Rarely,696,Sales,7,4,Marketing,...,2,80,1,12,3,3,11,7,1,9.0
1479,RM1210,60,55+,No,Travel_Rarely,370,Research & Development,1,4,Medical,...,3,80,1,19,2,4,1,0,0,0.0

In [6]:
len(df)

1480

In [7]:
df.shape

(1480, 38)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1480 entries, 0 to 1479
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1480 non-null   object
 1   Age                       1480 non-null   int64
 2   AgeGroup                  1480 non-null   object
 3   Attrition                 1480 non-null   object
 4   BusinessTravel            1480 non-null   object
 5   DailyRate                 1480 non-null   int64
 6   Department                1480 non-null   object
 7   DistanceFromHome          1480 non-null   int64
 8   Education                 1480 non-null   int64
 9   EducationField            1480 non-null   object
 10  EmployeeCount             1480 non-null   int64
 11  EmployeeNumber            1480 non-null   int64
 12  EnvironmentSatisfaction   1480 non-null   int64
 13  Gender                    1480 non-null   object
 14  HourlyRate                1480 non-null   int64
 15  JobInvolvement            1480 non-null   int64
 16  JobLevel                  1480 non-null   int64
 17  JobRole                   1480 non-null   object
 18  JobSatisfaction           1480 non-null   int64
 19  MaritalStatus             1480 non-null   object
 20  MonthlyIncome             1480 non-null   int64
 21  SalarySlab                1480 non-null   object
 22  MonthlyRate               1480 non-null   int64
 23  NumCompaniesWorked        1480 non-null   int64
 24  Over18                    1480 non-null   object
 25  OverTime                  1480 non-null   object
 26  PercentSalaryHike         1480 non-null   int64
 27  PerformanceRating         1480 non-null   int64
 28  RelationshipSatisfaction  1480 non-null   int64
 29  StandardHours             1480 non-null   int64
 30  StockOptionLevel          1480 non-null   int64
 31  TotalWorkingYears         1480 non-null   int64
 32  TrainingTimesLastYear     1480 non-null   int64
 33  WorkLifeBalance           1480 non-null   int64
 34  YearsAtCompany            1480 non-null   int64
 35  YearsInCurrentRole        1480 non-null   int64
 36  YearsSinceLastPromotion   1480 non-null   int64
 37  YearsWithCurrManager      1423 non-null   float64
dtypes: float64(1), int64(25), object(12)
memory usage: 439.5+ KB

In [9]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1480.000000,1480.000000,1480.000000,1480.000000,1480.0,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,...,1480.000000,1480.0,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1423.000000
mean,36.917568,801.384459,9.220270,2.910811,1.0,1031.860811,2.724324,65.845270,2.729730,2.064865,...,2.708784,80.0,0.791892,11.281757,2.797973,2.760811,7.009459,4.228378,2.182432,4.118060
std,9.128559,403.126988,8.131201,1.023796,0.0,605.955046,1.092579,20.328266,0.713007,1.105574,...,1.081995,0.0,0.850527,7.770870,1.288791,0.707024,6.117945,3.616020,3.219357,3.555484
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,493.750000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,800.000000,7.000000,3.000000,1.0,1027.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1568.250000,4.000000,83.000000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [10]:
print(df.columns)

Index(['EmpID', 'Age', 'AgeGroup', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'SalarySlab',
       'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [11]:
# Checking null values
df.isnull().sum()

EmpID                        0
Age                          0
AgeGroup                     0
Attrition                    0
BusinessTravel               0
DailyRate                    0
Department                   0
DistanceFromHome             0
Education                    0
EducationField               0
EmployeeCount                0
EmployeeNumber               0
EnvironmentSatisfaction      0
Gender                       0
HourlyRate                   0
JobInvolvement               0
JobLevel                     0
JobRole                      0
JobSatisfaction              0
MaritalStatus                0
MonthlyIncome                0
SalarySlab                   0
MonthlyRate                  0
NumCompaniesWorked           0
Over18                       0
OverTime                     0
PercentSalaryHike            0
PerformanceRating            0
RelationshipSatisfaction     0
StandardHours                0
StockOptionLevel             0
TotalWorkingYears            0
TrainingTimesLastYear        0
WorkLifeBalance              0
YearsAtCompany               0
YearsInCurrentRole           0
YearsSinceLastPromotion      0
YearsWithCurrManager        57
dtype: int64

###  Data Cleaning

In [12]:
df['YearsWithCurrManager']

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
1475    10.0
1476    11.0
1477     2.0
1478     9.0
1479     0.0
Name: YearsWithCurrManager, Length: 1480, dtype: float64

In [13]:
df['Department'].unique()

array(['Research & Development', 'Sales', 'Human Resources'], dtype=object)

In [14]:
# Handdle null values
df.groupby('YearsWithCurrManager')['Attrition'].value_counts()

YearsWithCurrManager  Attrition
0.0                   No           169
                      Yes           84
1.0                   No            65
                      Yes           11
2.0                   No           281
                      Yes           49
3.0                   No           121
                      Yes           18
4.0                   No            85
                      Yes           10
5.0                   No            27
                      Yes            4
6.0                   No            26
                      Yes            4
7.0                   No           181
                      Yes           30
8.0                   No            91
                      Yes            9
9.0                   No            56
                      Yes            5
10.0                  No            24
                      Yes            3
11.0                  No            20
                      Yes            1
12.0                  No            17
13.0                  No            14
14.0                  No             3
                      Yes            2
15.0                  No             5
16.0                  No             2
17.0                  No             6
Name: count, dtype: int64

In [15]:
# unstack() - converts output into table formate
df.groupby('YearsWithCurrManager')['Attrition'].value_counts().unstack()

Attrition                No   Yes
YearsWithCurrManager
0.0                   169.0  84.0
1.0                    65.0  11.0
2.0                   281.0  49.0
3.0                   121.0  18.0
4.0                    85.0  10.0
5.0                    27.0   4.0
6.0                    26.0   4.0
7.0                   181.0  30.0
8.0                    91.0   9.0
9.0                    56.0   5.0
10.0                   24.0   3.0
11.0                   20.0   1.0
12.0                   17.0   NaN
13.0                   14.0   NaN
14.0                    3.0   2.0
15.0                    5.0   NaN
16.0                    2.0   NaN
17.0                    6.0   NaN

In [16]:
df.groupby('YearsWithCurrManager')['Attrition'].value_counts().unstack().fillna(0, inplace=True)

In [17]:
df.isnull().sum()

EmpID                        0
Age                          0
AgeGroup                     0
Attrition                    0
BusinessTravel               0
DailyRate                    0
Department                   0
DistanceFromHome             0
Education                    0
EducationField               0
EmployeeCount                0
EmployeeNumber               0
EnvironmentSatisfaction      0
Gender                       0
HourlyRate                   0
JobInvolvement               0
JobLevel                     0
JobRole                      0
JobSatisfaction              0
MaritalStatus                0
MonthlyIncome                0
SalarySlab                   0
MonthlyRate                  0
NumCompaniesWorked           0
Over18                       0
OverTime                     0
PercentSalaryHike            0
PerformanceRating            0
RelationshipSatisfaction     0
StandardHours                0
StockOptionLevel             0
TotalWorkingYears            0
TrainingTimesLastYear        0
WorkLifeBalance              0
YearsAtCompany               0
YearsInCurrentRole           0
YearsSinceLastPromotion      0
YearsWithCurrManager        57
dtype: int64

In [18]:
#dropna=True  → remove null groups 
#dropna=False → include null groups
df.groupby('YearsWithCurrManager', dropna=False)['Attrition'].value_counts()

YearsWithCurrManager  Attrition
0.0                   No           169
                      Yes           84
1.0                   No            65
                      Yes           11
2.0                   No           281
                      Yes           49
3.0                   No           121
                      Yes           18
4.0                   No            85
                      Yes           10
5.0                   No            27
                      Yes            4
6.0                   No            26
                      Yes            4
7.0                   No           181
                      Yes           30
8.0                   No            91
                      Yes            9
9.0                   No            56
                      Yes            5
10.0                  No            24
                      Yes            3
11.0                  No            20
                      Yes            1
12.0                  No            17
13.0                  No            14
14.0                  No             3
                      Yes            2
15.0                  No             5
16.0                  No             2
17.0                  No             6
NaN                   No            49
                      Yes            8
Name: count, dtype: int64

In [19]:
df['YearsWithCurrManager'].fillna(df['YearsWithCurrManager'].median(), inplace=True)

In [20]:
df.isnull().sum()

EmpID                       0
Age                         0
AgeGroup                    0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
SalarySlab                  0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [21]:
df['Attrition'].value_counts()

Attrition
No     1242
Yes     238
Name: count, dtype: int64

In [22]:
df['Department'].value_counts()

Department
Research & Development    967
Sales                     450
Human Resources            63
Name: count, dtype: int64

In [23]:
pd.crosstab(df['Gender'], df['Attrition'])

Attrition   No  Yes
Gender
Female     504   87
Male       738  151

In [24]:
pd.crosstab(df['Department'], df['Attrition'])

Attrition                No  Yes
Department
Human Resources          51   12
Research & Development  834  133
Sales                   357   93

In [25]:
pd.crosstab(df['OverTime'], df['Attrition'])

Attrition   No  Yes
OverTime
No         952  110
Yes        290  128

In [26]:
pd.crosstab(df['YearsWithCurrManager'], df['Attrition'])

Attrition              No  Yes
YearsWithCurrManager
0.0                   169   84
1.0                    65   11
2.0                   281   49
3.0                   170   26
4.0                    85   10
5.0                    27    4
6.0                    26    4
7.0                   181   30
8.0                    91    9
9.0                    56    5
10.0                   24    3
11.0                   20    1
12.0                   17    0
13.0                   14    0
14.0                    3    2
15.0                    5    0
16.0                    2    0
17.0                    6    0

### Checking Duplicates

In [27]:
df.duplicated().sum()

np.int64(7)

In [28]:
df[df.duplicated()]  # Display all duplicate

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
211,RM1468,27,26-35,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,...,2,80,1,6,0,3,6,2,0,3.0
328,RM1461,29,26-35,No,Travel_Rarely,468,Research & Development,28,4,Medical,...,2,80,0,5,3,1,5,4,0,4.0
458,RM1464,31,26-35,No,Non-Travel,325,Research & Development,5,3,Medical,...,2,80,0,10,2,3,9,4,1,7.0
655,RM1470,34,26-35,No,TravelRarely,628,Research & Development,8,3,Medical,...,1,80,0,6,3,4,4,3,1,2.0
954,RM1463,39,36-45,No,Travel_Rarely,722,Sales,24,1,Marketing,...,1,80,1,21,2,2,20,9,9,6.0
1305,RM1469,49,46-55,No,Travel_Frequently,1023,Sales,2,3,Medical,...,4,80,0,17,3,2,9,6,0,8.0
1336,RM1462,50,46-55,Yes,Travel_Rarely,410,Sales,28,3,Marketing,...,2,80,1,20,3,3,3,2,2,0.0

In [29]:
df[df['EmpID']==1469]

Empty DataFrame
Columns: [EmpID, Age, AgeGroup, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeCount, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobRole, JobSatisfaction, MaritalStatus, MonthlyIncome, SalarySlab, MonthlyRate, NumCompaniesWorked, Over18, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StandardHours, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager]
Index: []

[0 rows x 38 columns]

In [30]:
df.duplicated(subset=['EmpID']).sum()

np.int64(10)

In [31]:
df.drop_duplicates(subset=['EmpID'], inplace=True)

In [32]:
df.duplicated(subset=['EmpID']).sum()

np.int64(0)

In [33]:
len(df)

1470

In [34]:
df.count()

EmpID                       1470
Age                         1470
AgeGroup                    1470
Attrition                   1470
BusinessTravel              1470
DailyRate                   1470
Department                  1470
DistanceFromHome            1470
Education                   1470
EducationField              1470
EmployeeCount               1470
EmployeeNumber              1470
EnvironmentSatisfaction     1470
Gender                      1470
HourlyRate                  1470
JobInvolvement              1470
JobLevel                    1470
JobRole                     1470
JobSatisfaction             1470
MaritalStatus               1470
MonthlyIncome               1470
SalarySlab                  1470
MonthlyRate                 1470
NumCompaniesWorked          1470
Over18                      1470
OverTime                    1470
PercentSalaryHike           1470
PerformanceRating           1470
RelationshipSatisfaction    1470
StandardHours               1470
StockOptionLevel            1470
TotalWorkingYears           1470
TrainingTimesLastYear       1470
WorkLifeBalance             1470
YearsAtCompany              1470
YearsInCurrentRole          1470
YearsSinceLastPromotion     1470
YearsWithCurrManager        1470
dtype: int64

In [35]:
df.columns

Index(['EmpID', 'Age', 'AgeGroup', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'SalarySlab',
       'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [2]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages (9.6.0)

In [6]:
import mysql.connector

In [1]:
import pandas as pd

In [4]:
pip install --upgrade mysql-connector

Requirement already satisfied: mysql-connector in C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.2.9)
Note: you may need to restart the kernel to use updated packages.

In [5]:
!python.exe -m pip install --upgrade pip

Requirement already satisfied: pip in C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages (26.0.1)

In [7]:
db = mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password="shivam@123",
    database="hr_analysis"
)

mycursor = db.cursor()
print(db)

print("Hi, THe database is connected")

<mysql.connector.connection_cext.CMySQLConnection object at 0x000001B49FBB7D40>
Hi, THe database is connected

In [8]:
mycursor.execute("""
CREATE TABLE IF NOT EXISTS hrdata(
    EmpID VARCHAR(20) PRIMARY KEY,
    Age INT NOT NULL,
    AgeGroup INT NOT NULL,
    Attrition VARCHAR(5) NOT NULL,
    BusinessTravel VARCHAR(50),
    DailyRate INT,
    Department VARCHAR(50),
    DistanceFromHome INT,
    Education INT,
    EducationField VARCHAR(50),
    EmployeeCount INT,
    EmployeeNumber INT PRIMARY KEY,
    EnvironmentSatisfaction INT,
    Gender VARCHAR(10),
    HourlyRate INT,
    JobInvolvement INT,
    JobLevel INT,
    JobRole VARCHAR(50),
    JobSatisfaction INT,
    MaritalStatus VARCHAR(20),
    MonthlyIncome INT,
    SalarySlab VARCHAR(20),
    MonthlyRate INT,
    NumCompaniesWorked INT,
    Over18 VARCHAR(5),
    OverTime VARCHAR(10),
    PercentSalaryHike INT,
    PerformanceRating INT,
    RelationshipSatisfaction INT,
    StandardHours INT,
    StockOptionLevel INT,
    TotalWorkingYears INT,
    TrainingTimesLastYear INT,
    WorkLifeBalance INT,
    YearsAtCompany INT,
    YearsInCurrentRole INT,
    YearsSinceLastPromotion INT,
    YearsWithCurrManager INT
)
""")

db.commit()
print("✅ Table created")

ProgrammingError: 1068 (42000): Multiple primary key defined

In [9]:
mycursor.execute("SHOW TABLES")

for table in mycursor.fetchall():
    print(table)

In [8]:
!pip install pymysql

Requirement already satisfied: pymysql in C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages (1.1.2)

In [17]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:shivam%40123@localhost/hr_analysis")

In [11]:
# importing dataset
df = pd.read_csv("HR_Analytics.csv")
print("dataset loaded")

dataset loaded

In [18]:
df.to_sql(
    name='hrdata',     # new table name
    con=engine,
    if_exists='replace',   # delete old if exists
    index=False
)

print("✅ New table created & data inserted")

✅ New table created & data inserted

In [19]:
import mysql.connector

db = mysql.connector.connect(
    host="localhost",
    user="root",
    password="shivam@123",
    database="hr_analysis"
)

cursor = db.cursor()

In [16]:
cursor.execute("SHOW TABLES")
print(cursor.fetchall())

[('hrdata',)]

In [20]:
cursor.execute("SELECT * FROM hrdata LIMIT 5")

for row in cursor.fetchall():
    print(row)

('RM297', 18, '18-25', 'Yes', 'Travel_Rarely', 230, 'Research & Development', 3, 3, 'Life Sciences', 1, 405, 3, 'Male', 54, 3, 1, 'Laboratory Technician', 3, 'Single', 1420, 'Upto 5k', 25233, 1, 'Y', 'No', 13, 3, 3, 80, 0, 0, 2, 3, 0, 0, 0, 0.0)
('RM302', 18, '18-25', 'No', 'Travel_Rarely', 812, 'Sales', 10, 3, 'Medical', 1, 411, 4, 'Female', 69, 2, 1, 'Sales Representative', 3, 'Single', 1200, 'Upto 5k', 9724, 1, 'Y', 'No', 12, 3, 1, 80, 0, 0, 2, 3, 0, 0, 0, 0.0)
('RM458', 18, '18-25', 'Yes', 'Travel_Frequently', 1306, 'Sales', 5, 3, 'Marketing', 1, 614, 2, 'Male', 69, 3, 1, 'Sales Representative', 2, 'Single', 1878, 'Upto 5k', 8059, 1, 'Y', 'Yes', 14, 3, 4, 80, 0, 0, 3, 3, 0, 0, 0, 0.0)
('RM728', 18, '18-25', 'No', 'Non-Travel', 287, 'Research & Development', 5, 2, 'Life Sciences', 1, 1012, 2, 'Male', 73, 3, 1, 'Research Scientist', 4, 'Single', 1051, 'Upto 5k', 13493, 1, 'Y', 'No', 15, 3, 4, 80, 0, 0, 2, 3, 0, 0, 0, 0.0)
('RM829', 18, '18-25', 'Yes', 'Non-Travel', 247, 'Research & Development', 8, 1, 'Medical', 1, 1156, 3, 'Male', 80, 3, 1, 'Laboratory Technician', 3, 'Single', 1904, 'Upto 5k', 13556, 1, 'Y', 'No', 12, 3, 4, 80, 0, 0, 0, 3, 0, 0, 0, 0.0)